apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - "../../base"

patches:
  - path: api-ingress-patch.json
    target:
      kind: Ingress
      name: core-server
  - path: dl-ingress-patch.json
    target:
      kind: Ingress
      name: core-server-downloader